version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: mongo
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/myapp --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  data:
